### ISSUE TITLE
Failed to activate the gpd package

### ISSUE THREAD

**Issue by giampierod** [giampierod/gpd.atom#6]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [gpd](https://github.com/giampierod/gpd.atom) package 0.15.4

### Stack Trace

Failed to activate the gpd package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/composite-disposable.js:74:1)
    at CompositeDisposable.module.exports.CompositeDisposable.add (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/composite-disposable.js:43:1)
    at Package.module.exports.Package.activateKeymaps (/Applications/Atom.app/Contents/Resources/app/src/package.js:374:1)
    at Package.module.exports.Package.activateResources (/Applications/Atom.app/Contents/Resources/app/src/package.js:341:1)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:1
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:1)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:1
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:1)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:642:1)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:623:1
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:346:1)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:618:1)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:600:1)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:832:1
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.24 
atom-math 0.0.9 
busy-signal 1.4.1 
column-select 0.2.0 
git-control 0.9.0 
gpd 0.15.4 
intentions 1.1.2 
isotope-ui 2.8.0 
language-powershell 4.0.0 
linter 2.1.4 
linter-ui-default 1.4.0 
pretty-json 1.6.3 
unity-dark-ui 2.0.9 
```

**Comment by jkamenik** [comment]
I am getting the same issue.  My non-core packages are

```
advanced-open-file 0.16.6
atom-fuzzy-grep 0.16.0
column-select 0.2.0
editorconfig 2.2.2
emacs-flow 0.1.2
git-plus 7.8.0
gpd 0.15.4
highlight-selected 0.13.1
language-docker 1.1.7
language-groovy 0.7.0
language-lua 0.9.11
language-puppet 0.22.0
language-scala 1.1.8
markdown-folding 0.1.0
markdown-writer 2.6.5
minimap 4.28.2
minimap-bookmarks 0.4.2
minimap-cursorline 0.2.0
minimap-highlight-selected 4.6.1
nvatom 0.11.0
tablr 1.8.3
tabularize 0.2.5
term3 0.22.1
theme-switcher 1.1.0
```

**Comment by jkamenik** [comment]
I disable the following and no longer get the issue:

```
emacs-flow
git-plus
gpd
markdown-writer
```

From the list of shared plugins I think the issue is `gpd`.

**Comment by giampierod** [comment]
Yes it is... but I don't know why. I have been trying to debug this for the last day but cannot figure out what is causing it. I am on the Slack channel with the atom team to hope to get some answers.

**Comment by giampierod** [comment]
It was an issue with the keymaps/gpd.cson file. The lines with the license text failed a formatting check. This was ignored before, but I guess they got more strict. It is fixed in the latest now.
